#!/usr/bin/env bash
# Write .nexusflow/airflow_elt.env for Airflow → nexus-elt docker run --env-file.
# Invoked by ./scripts/start.sh after secrets are loaded. Not for interactive use.
# Re-run via ./scripts/start.sh airflow after Vault password rotation.
#
# Docker --env-file: KEY=VALUE per line; value is literal after the first '='
# (no quote stripping, no escape sequences). Newlines in values are invalid.
# Write to a temp file then rename so a failed validation never truncates a good file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

out="${NEXUS_AIRFLOW_ELT_ENV:-${ROOT}/.nexusflow/airflow_elt.env}"
mkdir -p "$(dirname "${out}")"

# Keys the warehouse ELT job needs. Hostnames are overridden to Compose DNS in
# nexus_elt_exec.py (clickhouse / minio / otel-collector).
keys=(
  NEXUS_ENV
  AWS_REGION
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  MINIO_API_PORT
  MINIO_LOADER_USER
  MINIO_LOADER_PASSWORD
  CLICKHOUSE_DB
  CLICKHOUSE_HTTP_PORT
  CLICKHOUSE_NATIVE_PORT
  CLICKHOUSE_USER
  CLICKHOUSE_PASSWORD
  CLICKHOUSE_LOADER_USER
  CLICKHOUSE_LOADER_PASSWORD
  CLICKHOUSE_TRANSFORMER_USER
  CLICKHOUSE_TRANSFORMER_PASSWORD
  CLICKHOUSE_READER_USER
  CLICKHOUSE_READER_PASSWORD
  CLICKHOUSE_ADMIN_USER
  CLICKHOUSE_ADMIN_PASSWORD
  CLICKHOUSE_CATALOG_USER
  CLICKHOUSE_CATALOG_PASSWORD
  OPENMETADATA_ADMIN_EMAIL
  OPENMETADATA_ADMIN_PASSWORD
  OPENMETADATA_URL
  OPENMETADATA_VERSION
  # Public Caddy hostnames for OM CustomDashboard sourceUrl (not Compose DNS).
  NEXUS_PUBLIC_HOST
  NEXUS_CADDY_SITE_SCHEME
  # Optional R2/S3 archive backup (ops_backup_archive DAG / backup-archive.sh).
  NEXUS_BACKUP_ENDPOINT
  NEXUS_BACKUP_ACCESS_KEY
  NEXUS_BACKUP_SECRET_KEY
)

# Warehouse job S3 defaults are the MinIO loader, not root.
if [[ -z "${MINIO_LOADER_USER:-}" || -z "${MINIO_LOADER_PASSWORD:-}" ]]; then
  echo "MINIO_LOADER_USER and MINIO_LOADER_PASSWORD are required (Vault minio_loader)." >&2
  exit 1
fi
export AWS_ACCESS_KEY_ID="${MINIO_LOADER_USER}"
export AWS_SECRET_ACCESS_KEY="${MINIO_LOADER_PASSWORD}"
: "${AWS_REGION:=us-east-1}"
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION

write_kv() {
  local key="$1"
  local value="$2"
  # Docker env-file is line-delimited; CR/LF would split or corrupt the file.
  if [[ "${value}" == *$'\n'* || "${value}" == *$'\r'* ]]; then
    echo "Refusing to write ${key}: value contains a newline (invalid for docker --env-file)" >&2
    return 1
  fi
  printf '%s=%s\n' "${key}" "${value}"
}

tmp="$(mktemp "${out}.XXXXXX")"
cleanup_tmp() {
  rm -f "${tmp}"
}
trap cleanup_tmp EXIT

{
  echo "# Generated by scripts/airflow-write-elt-env.sh — do not commit"
  for key in "${keys[@]}"; do
    if [[ -n "${!key+x}" ]]; then
      write_kv "${key}" "${!key}"
    fi
  done
} >"${tmp}"

chmod 600 "${tmp}"
mv -f "${tmp}" "${out}"
trap - EXIT
echo "Wrote ${out}"
