#!/usr/bin/env bash
# Write .nexusflow/airflow_elt.env for Airflow → nexus-elt docker run --env-file.
# Invoked by ./scripts/start.sh after secrets are loaded. Not for interactive use.
# Re-run via ./scripts/start.sh airflow after Vault password rotation.
#
# Docker --env-file: KEY=VALUE per line; value is literal after the first '='
# (no quote stripping, no escape sequences). Newlines in values are invalid.
# Write to a temp file then rename so a failed validation never truncates a good file.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

out="${NEXUS_AIRFLOW_ELT_ENV:-${ROOT}/.nexusflow/airflow_elt.env}"
mkdir -p "$(dirname "${out}")"

# Keys the warehouse ELT job needs. Hostnames are overridden to Compose DNS in
# nexus_elt_exec.py (clickhouse / minio / otel-collector).
keys=(
  NEXUS_ENV
  AWS_REGION
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
  MINIO_API_PORT
  CLICKHOUSE_DB
  CLICKHOUSE_HTTP_PORT
  CLICKHOUSE_NATIVE_PORT
  CLICKHOUSE_USER
  CLICKHOUSE_PASSWORD
  CLICKHOUSE_LOADER_USER
  CLICKHOUSE_LOADER_PASSWORD
  CLICKHOUSE_TRANSFORMER_USER
  CLICKHOUSE_TRANSFORMER_PASSWORD
  CLICKHOUSE_READER_USER
  CLICKHOUSE_READER_PASSWORD
  CLICKHOUSE_ADMIN_USER
  CLICKHOUSE_ADMIN_PASSWORD
)

# MinIO S3 client defaults when AWS_* are unset (local Compose).
: "${AWS_ACCESS_KEY_ID:=${MINIO_ROOT_USER:-minioadmin}}"
: "${AWS_SECRET_ACCESS_KEY:=${MINIO_ROOT_PASSWORD:-minioadmin123}}"
: "${AWS_REGION:=us-east-1}"
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION

write_kv() {
  local key="$1"
  local value="$2"
  # Docker env-file is line-delimited; CR/LF would split or corrupt the file.
  if [[ "${value}" == *$'\n'* || "${value}" == *$'\r'* ]]; then
    echo "Refusing to write ${key}: value contains a newline (invalid for docker --env-file)" >&2
    return 1
  fi
  printf '%s=%s\n' "${key}" "${value}"
}

tmp="$(mktemp "${out}.XXXXXX")"
cleanup_tmp() {
  rm -f "${tmp}"
}
trap cleanup_tmp EXIT

{
  echo "# Generated by scripts/airflow-write-elt-env.sh — do not commit"
  for key in "${keys[@]}"; do
    if [[ -n "${!key+x}" ]]; then
      write_kv "${key}" "${!key}"
    fi
  done
} >"${tmp}"

chmod 600 "${tmp}"
mv -f "${tmp}" "${out}"
trap - EXIT
echo "Wrote ${out}"
