#!/usr/bin/env python3
"""Render otel-collector config: lake awss3 + optional SigNoz / OpenObserve exporters.

Reads docker/otel/collector-config.yaml (receivers + lake exporter) and writes
docker/otel/.generated/collector-config.yaml with reader exporters when those
Compose profiles are running. Also injects prometheus/clickhouse when the
clickhouse profile is up (avoids scrape noise when warehouse is stopped).

Usage:
  uv run python scripts/render-otel-collector-config.py
  uv run python scripts/render-otel-collector-config.py --signoz --openobserve --clickhouse
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BASE = REPO_ROOT / "docker" / "otel" / "collector-config.yaml"
OUT_DIR = REPO_ROOT / "docker" / "otel" / ".generated"
OUT = OUT_DIR / "collector-config.yaml"

SIGNOZ_EXPORTER = """
  otlp/signoz:
    endpoint: signoz:4317
    tls:
      insecure: true
    sending_queue:
      enabled: true
""".rstrip(
    "\n"
)

OPENOBSERVE_EXPORTER = """
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_OTLP_BASIC_AUTH}"
    tls:
      insecure: true
    sending_queue:
      enabled: true
""".rstrip(
    "\n"
)

CLICKHOUSE_RECEIVER = """
  prometheus/clickhouse:
    config:
      scrape_configs:
        - job_name: clickhouse
          scrape_interval: 60s
          metrics_path: /metrics
          static_configs:
            - targets: ["clickhouse:9363"]
              labels:
                service.name: nexusflow.clickhouse
""".rstrip(
    "\n"
)

METRICS_RECEIVERS_BASE = "receivers: [otlp, prometheus/self, docker_stats]"
METRICS_RECEIVERS_WITH_CH = (
    "receivers: [otlp, prometheus/self, prometheus/clickhouse, docker_stats]"
)


def profile_running(profile: str, service: str) -> bool:
    result = subprocess.run(
        [
            "docker",
            "compose",
            "--profile",
            profile,
            "ps",
            service,
            "--status",
            "running",
            "-q",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return bool(result.stdout.strip())


def inject_exporters(text: str, blocks: list[str], names: list[str]) -> str:
    if not names:
        return text
    # Insert reader exporters after the awss3 block (before blank line + "service:").
    marker = "    marshaler: otlp_json\n"
    insert_at = text.find(marker)
    if insert_at < 0:
        raise SystemExit("ERROR: could not find awss3 marshaler marker in base config")
    insert_at += len(marker)
    extra = "\n" + "\n".join(blocks) + "\n"
    text = text[:insert_at] + extra + text[insert_at:]

    exporter_list = ", ".join(["awss3", *names])
    text = re.sub(
        r"(^\s+exporters:\s*)\[awss3\]",
        rf"\1[{exporter_list}]",
        text,
        flags=re.MULTILINE,
    )
    return text


def inject_clickhouse_receiver(text: str, *, enabled: bool) -> str:
    """Add or omit prometheus/clickhouse scrape based on warehouse profile."""
    if not enabled:
        return text
    # Insert after docker_stats block ends (before httpcheck comment / httpcheck:).
    anchor = "\n  httpcheck:\n"
    insert_at = text.find(anchor)
    if insert_at < 0:
        raise SystemExit("ERROR: could not find httpcheck receiver anchor in base config")
    text = text[:insert_at] + "\n" + CLICKHOUSE_RECEIVER + "\n" + text[insert_at:]
    if METRICS_RECEIVERS_BASE not in text:
        raise SystemExit(
            f"ERROR: expected metrics pipeline {METRICS_RECEIVERS_BASE!r} in base config"
        )
    return text.replace(METRICS_RECEIVERS_BASE, METRICS_RECEIVERS_WITH_CH, 1)


def render(*, signoz: bool, openobserve: bool, clickhouse: bool) -> Path:
    base = BASE.read_text(encoding="utf-8")
    header = (
        "# GENERATED by scripts/render-otel-collector-config.py — do not edit.\n"
        f"# Readers: signoz={signoz} openobserve={openobserve} clickhouse={clickhouse}\n"
    )
    blocks: list[str] = []
    names: list[str] = []
    if signoz:
        blocks.append(SIGNOZ_EXPORTER)
        names.append("otlp/signoz")
    if openobserve:
        blocks.append(OPENOBSERVE_EXPORTER)
        names.append("otlphttp/openobserve")

    body = inject_clickhouse_receiver(base, enabled=clickhouse)
    body = inject_exporters(body, blocks, names)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + body, encoding="utf-8")
    return OUT


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--signoz",
        action="store_true",
        help="Force SigNoz exporter on (default: detect running container)",
    )
    parser.add_argument(
        "--openobserve",
        action="store_true",
        help="Force OpenObserve exporter on (default: detect running container)",
    )
    parser.add_argument(
        "--clickhouse",
        action="store_true",
        help="Force ClickHouse prometheus scrape on (default: detect running container)",
    )
    parser.add_argument(
        "--detect",
        action="store_true",
        default=True,
        help="Detect running reader/warehouse containers (default)",
    )
    parser.add_argument(
        "--no-detect",
        action="store_true",
        help="Do not detect; only use --signoz / --openobserve / --clickhouse flags",
    )
    args = parser.parse_args(argv)

    signoz = bool(args.signoz)
    openobserve = bool(args.openobserve)
    clickhouse = bool(args.clickhouse)
    if not args.no_detect:
        signoz = signoz or profile_running("signoz", "signoz")
        openobserve = openobserve or profile_running("openobserve", "openobserve")
        clickhouse = clickhouse or profile_running("clickhouse", "clickhouse")

    out = render(signoz=signoz, openobserve=openobserve, clickhouse=clickhouse)
    print(
        f"Wrote {out.relative_to(REPO_ROOT)} "
        f"(signoz={signoz} openobserve={openobserve} clickhouse={clickhouse})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
